name: Deploy Laravel Project on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      LARAVEL_BYPASS_ENV_CHECK: 1  # Set the environment variable
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Set DB_DATABASE, DB_USERNAME, DB_PASSWORD, MAIL_HOST, MAIL_USERNAME and MAIL_PASSWORD
        run: |
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env
          sed -i "s/MAIL_HOST=.*/MAIL_HOST=${{ secrets.MAIL_HOST }}/" .env
          sed -i "s/MAIL_USERNAME=.*/MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}/" .env
          sed -i "s/MAIL_PASSWORD=.*/MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}/" .env
          sed -i "s/APP_ENV=.*/APP_ENV=production/" .env
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear Application Cache
        run: php artisan cache:clear
      - name: Compile Assets (npm run dev)
        run: npm install && npm run build
      - name: Debug FTP Configuration
        run: echo "FTP_SERVER=${{ secrets.FTP_SERVER }} FTP_USERNAME=${{ secrets.FTP_USERNAME }} FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}"
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          port: 2221
          timeout: 10 minutes